# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: terrascan

on:
  push:
    branches:
      - dev
      - staging
    paths:
      - prod/**
  pull_request:
    branches:
      - prod
    paths:
      - prod/**

jobs:
  terrascan_tflint_staging:
    name: Run Terrascan sarif report
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | jq -r .assets[].browser_download_url | grep 'linux_amd64' | head -n 1)" > terrascan.zip
          unzip terrascan.zip
          sudo mv terrascan /usr/local/bin/
          terrascan version

      - name: Init Terrascan
        run: terrascan init
        working-directory: ./prod

      - name: Run Terrascan
        run: terrascan scan -o sarif
        working-directory: ./prod
        env:
          TERRASCAN_OPTIONS: "--exit-code 1" # Adjust options as needed

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan.sarif
